### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by nikunjOceanmtech** [cunarist/rinf#382] opened 2024-06-19 06:35 UTC
@temeddix , 

i am create new flutter project then add **rinf: ^6.12.1** this package then follow this website
https://rinf.cunarist.com/applying-template/
and then method call to show same error

https://github.com/cunarist/rinf/assets/147715598/1216cb36-1e52-4ad4-b1f5-5979fa319b87

<image src="https://github.com/cunarist/rinf/assets/147715598/1216cb36-1e52-4ad4-b1f5-5979fa319b87">

**Comment by temeddix** [comment] 2024-06-19 10:47
I see you have another issue here. Right now the codebase is undergoing a refactor, so please wait until I investigate. Thank you for your patience :)

**Comment by temeddix** [comment] 2024-06-23 15:31
Closing as duplicate of #368

**Closed as completed** 2024-06-23 15:31 UTC
