### ISSUE TITLE
Compile rust in release mode

### ISSUE THREAD

**Issue by filip-alexandrov** [cunarist/rinf#59] opened 2023-07-15 13:47 UTC
When running
```
flutter build apk --release
```
the rust code is compiled in dev mode: 
```
Finished dev [unoptimized + debuginfo] target(s) in 0.08s
```
Is it possible to pass `--release` flag to the `rust build` command?

**Comment by temeddix** [comment] 2023-07-15 14:57
Hmm, it's weird that Rust is compiled in debug mode when building for Android in release mode. I'll check this issue and share the progress. Thanks for reporting!

**Comment by filip-alexandrov** [comment] 2023-07-15 15:28
Here is more info: 
To replicate, run one of the commands:

- `flutter build apk --release`
- `flutter run --release`
- `flutter run` 

in the example folder of the project. The output is identical with regards to rust: 
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `/Users/faa/Documents/GitHub/flutter-experiments/rust-in-flutter/example/build/rust_in_flutter/build/rust_tool/debug/build_tool build_android`
```

Thanks for developing this package :)

**Comment by temeddix** [comment] 2023-07-15 19:35
I checked the behavior of the code, and the output does use Rust code compiled in release mode as expected. It can be tested by modifying some code in `sample_functions.rs`
```rust
...
            let before_value = received.before_number;
            let after_value;
            // Check if the build mode is 'debug' or 'release'
            #[cfg(debug_assertions)]
            {
                after_value = before_value + 1;
            }
            #[cfg(not(debug_assertions))]
            {
                after_value = before_value + 10;
            }
...
```

With `flutter run --release`, the numbers get added by 10, not 1. So it IS being properly compiled in release mode.

Since this is an issue with [cargokit](https://github.com/irondash/cargokit), we should dive into the code there to inspect deeper. However, I can say that build mode is working as expected for now :) Thank you for your valuable question!

**Comment by temeddix** [comment] 2023-07-16 03:58
But I'm still trying to investigate why the terminal output was being written like that... that's still the mysterious part

**Comment by temeddix** [comment] 2023-07-16 04:22
It turned out that `Finished dev [unoptimized + debuginfo] target(s) in 0.09s` output was from the `build_tool` crate inside a connector between Flutter and Rust. It was not from our real crates in our Flutter project, which were being compiled in release mode as expected. Commit 7a731b5 solves this issue by hiding the output of `cargo run ... build_tool` and the problem is fixed in the 1.2.6 release.

Thank you for pointing this out. Always feel free to come back if there are other issues!

**Comment by filip-alexandrov** [comment] 2023-07-16 08:18
Much of my confusion came from performance discrepancy between the tokio runtime and standard rust while evaluating a math-heavy test function. There seems to have been some unaccounted optimization by the rust compiler. Here a revised benchmark, confirming the right comilation mode: 
```rs
fn fibonacci(n: u32) -> u128 {
    if n <= 1 {
        return 0;
    }

    let mut a: u128 = 0;
    let mut b: u128 = 1;

    // execute the fibonacci sequence 10 million times
    let total_loops = 10_000_000;
    let mut count = 0;

    let start = Instant::now();

    loop {
        for _ in 2..=n {
            let temp = a + b;
            a = b;
            b = temp;
        }

        // reset the fibonacci sequence to prevent overflow
        if b > 35422484817926100 {
            count += 1;
            a = 0;
            b = 1;
        }

        if count == total_loops {
            let duration = start.elapsed();
            println!("Execution time: {:?}", duration);
            return duration.as_millis();
        }
    }
}
```

*1. Standard rust on M1 Pro* 
```rs
fn main() {
    // Perform a computationally intensive task
    let result: u128 = fibonacci(50);
}
```
Release mode: `Execution time: 516ms`
Dev mode: `Execution time: 10s`

*2. Tokio runtime with std thread on M1 Pro* 
```rs
#[tokio::main]
async fn main() {
    let join_handle = spawn(move || fibonacci(50));

    let result = join_handle.join().unwrap();
}
```
Release mode: `Execution time: 964ms`
Dev mode: `Execution time: 9s`

*3. Tokio runtime with blocking thread on M1 Pro* 
```rs
#[tokio::main]
async fn main() {
    let join_handle = spawn_blocking(move || fibonacci(50));

    let result = join_handle.await.unwrap();
}
```
Relese mode: `Execution time: 972ms`
Dev mode: `Execution time: 8.19s`

*4. Flutter Emulator with Tokio*

Relese mode: `Execution time: 999ms`
Dev mode: `Execution time: 12s`

**Comment by temeddix** [comment] 2023-07-16 08:46
Hmm, yes it does look like Tokio's `spawn` or `spawn_blocking` slows things a bit down compared to pure Rust. It's interesting that Tokio is slower at blocking tasks :\

**Closed as completed by temeddix** 2023-07-16 08:46 UTC

**Comment by temeddix** [comment] 2023-07-16 08:49
Perhaps it's because of the duration of the async runtime execution. I wonder what would happen if you measure the time _inside_ that main function, not the whole execution time, like this:

```rust
#[tokio::main]
fn main() {
    use std::time::Instant;
    let now = Instant::now();

    let join_handle = spawn_blocking(move || fibonacci(50));
    let result = join_handle.await.unwrap();

    let elapsed = now.elapsed();
    println!("Elapsed: {:.2?}", elapsed);
}
```
